version: '3.1'
services:
  docker-postgres:
    restart: always
    container_name: shipsdb
    image: postgres:12.6
    environment:
      POSTGRES_DB: ships
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "8432:5432"
    volumes:
      -  docker-postgres-data:/var/lib/postgresql/data


  prometheus:
    image: prom/prometheus:v2.26.1
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  docker-postgres-data:
  prometheus-data:
  grafana-data: